server:
  address: 127.0.0.1
  port: 8082
  # servlet:
  #   context-path: /gestion

spring:
  application:
    name: servicio-gestion
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    username: ${DB_USERNAME:user_hc}
    password: ${DB_PASSWORD:secure_password_2025}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties: {}

ficha:
  archivos:
    ftp:
      enabled: false

app:
  debug:
    controllers:
      enabled: false
  controllers:
    fichas:
      enabled: true

