server:
  address: 0.0.0.0
  port: 8081

spring:
  application:
    name: servicio-catalogos
  datasource:
    # Permite usar la BD local por defecto o sobreescribir via variables (ideal para Docker)
    # En Docker usaremos: DB_HOST=oracle-db, DB_PORT=1521, DB_SERVICE=FREEPDB1
    url: jdbc:oracle:thin:@${DB_HOST:localhost}:${DB_PORT:1521}/${DB_SERVICE:xepdb1}
    username: ${DB_USERNAME:user_hc}
    password: ${DB_PASSWORD:secure_password_2025}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
  jmx:
    enabled: false

security:
  roles:
    admin: ADMINISTRADOR
    psychologist: PSICOLOGO
  jwt:
    secret: ${JWT_SECRET:cambia-esta-clave-super-segura-de-32+caracteres-2025}
    issuer: ${JWT_ISSUER:modulo-evaluaciones-psicologicas}
    audience: ${JWT_AUDIENCE:frontend-clients}
  dev:
    plainAuth: true

services:
  gestion:
    base-url: ${SERVICIO_GESTION_URL:http://127.0.0.1:8082}
